// Dados-base do Radar de Prospeção Naloa, organizados por secção.
// Cada linha: id, secção, data, nome, sub, local, ângulo, link (dados originais)
// + redes_sociais / site / contacto / notas (pesquisados).

export const sections = [
  {
    key: "motorsport",
    label: "Motorsport",
    tag: "evento datado",
    note: "A tua maior vantagem: acesso MEDIA FPAK. Automóveis primeiro, sempre — portfolio já feito desde 2021.",
  },
  {
    key: "crosssell",
    label: "Cross-sell auto/moto",
    tag: "pitch recorrente",
    note: "Leads já prospetados para web — segunda conversa fácil, contacto já existe.",
  },
  {
    key: "feiras",
    label: "Feiras B2B — conteúdo para expositores",
    tag: "evento datado",
    note: "As feiras grandes e conhecidas (WSBK, Web Summit, ModaLisboa) já têm cobertura oficial fechada com agências — baixa prioridade, marcadas abaixo. As feiras pequenas da Exponor (a maioria) são onde os expositores individuais normalmente não têm ninguém a fazer conteúdo próprio.",
  },
  {
    key: "imobiliario",
    label: "Imobiliário de luxo",
    tag: "pitch recorrente",
    note: "Sem feiras no calendário até dezembro (SIL/MIPIM já passaram). A oportunidade é conteúdo fixo por imóvel, não evento.",
  },
  {
    key: "barcos",
    label: "Barcos / iates",
    tag: "pitch recorrente",
    note: "Nauticampo (Lisboa Boat Show) já foi em março — fora da janela. Mesma lógica do imobiliário: conteúdo por anúncio.",
  },
  {
    key: "vinhos",
    label: "Vinhos & gastronomia",
    tag: "misto",
    note: "Essência do Vinho e vindimas já passaram (fev-set). O que resta na janela é pequena escala e tradição local — mercados de Natal são grandes e saturados.",
  },
  {
    key: "hoteis",
    label: "Congressos médicos em hotéis",
    tag: "evento datado",
    note: "Salas de hotel não têm calendário público próprio — isto veio de agendas de congressos médicos/farmacêuticos, que reservam essas salas constantemente. Patrocinadores farmacêuticos com orçamento, sem fotógrafo dedicado, quase ninguém a competir.",
  },
  {
    key: "outros",
    label: "Moda / tecnologia / hotelaria / música",
    tag: "exploratório",
    note: "Nestes quatro, pouco de concreto para out–dez além do que já está listado acima.",
  },
  {
    key: "continental",
    label: "Portugal Continental — fins de semana",
    tag: "evento datado",
    note: "Fora de Lisboa/Porto, vale a pena se o pagamento/prestígio cobrir viagem + estadia e ainda sobrar lucro. Aqui entram surf (a tua zona), cavalos de elite, rallies com equipas patrocinadas, e congressos médicos fora de Lisboa/Porto.",
  },
];

export const leads = [
  // ---- Motorsport ----
  { id: "ms-wsbk", section: "motorsport", date_label: "10–11 out", start_date: "2026-10-10", end_date: "2026-10-11",
    name: "WSBK — Mundial Superbikes", sub: "Evento grande — cobertura oficial já garantida, baixa prioridade para pitch",
    local: "Estoril", angle: "Vale ir para portfolio/networking, não para vender cobertura",
    link: "https://www.circuito-estoril.pt/en/eventos/",
    redes_sociais: "IG: @circuitoestoril (circuito); IG evento: @sbkestoril", site: "circuito-estoril.pt/eventos/wsbk-2026 · bilhetes: sbkestoril.com",
    contacto: "correio.geral@circuito-estoril.pt · +351 21 460 95 00",
    notas: "Contacto é do circuito; venda de bilhetes é gerida à parte pela SBK Estoril" },
  { id: "ms-benjafield", section: "motorsport", date_label: "26–27 set", start_date: "2026-09-26", end_date: "2026-09-27",
    name: "Benjafield's 500", sub: "Clássicos / histórico", local: "Estoril",
    angle: "Público de colecionadores — bom para posters/prints",
    link: "https://www.circuito-estoril.pt/en/eventos/",
    redes_sociais: "IG/FB: @circuitoestoril", site: "circuito-estoril.pt/eventos/bentley-boys",
    contacto: "correio.geral@circuito-estoril.pt · +351 21 460 95 00",
    notas: "Página tem info limitada; redes/contacto são do circuito, não do evento" },
  { id: "ms-cnv4", section: "motorsport", date_label: "3–4 out", start_date: "2026-10-03", end_date: "2026-10-04",
    name: "CNV #4 — motos", sub: null, local: "Estoril",
    angle: "Classes júnior — pais/equipas querem memórias em vídeo",
    link: "https://www.circuito-estoril.pt/en/eventos/",
    redes_sociais: "IG/FB: @circuitoestoril", site: "circuito-estoril.pt/en/eventos/cnv-4-2026",
    contacto: "correio.geral@circuito-estoril.pt · +351 21 460 95 00",
    notas: "Redes/contacto são do circuito, não do evento" },
  { id: "ms-caramulo", section: "motorsport", date_label: "24–25 out", start_date: "2026-10-24", end_date: "2026-10-25",
    name: "Rampa do Caramulo", sub: "Onde começaste em 2021", local: "Caramulo (perto Tondela)",
    angle: "Ângulo pessoal para post de LinkedIn + perto do lead Tondel Motors",
    link: "https://www.fpak.pt/calendario",
    redes_sociais: "FB: facebook.com/rampadocaramulo", site: "—",
    contacto: "faleconnosco@fpak.pt (FPAK)",
    notas: "Site oficial rampadocaramulo.pt inativo; contacto é da federação (FPAK), não do evento" },
  { id: "ms-acf", section: "motorsport", date_label: "30 out – 1 nov", start_date: "2026-10-30", end_date: "2026-11-01",
    name: "ACF Endurance", sub: null, local: "Estoril", angle: "—",
    link: "https://www.circuito-estoril.pt/en/eventos/",
    redes_sociais: "IG/FB: @circuitoestoril", site: "circuito-estoril.pt/eventos",
    contacto: "correio.geral@circuito-estoril.pt · +351 21 460 95 00",
    notas: "Página dedicada 'ACF Endurance' não confirmada; possível confusão com Algarve Classic Festival" },
  { id: "ms-endurofest", section: "motorsport", date_label: "4–6 dez", start_date: "2026-12-04", end_date: "2026-12-06",
    name: "Estoril Endurance Festival", sub: "Fecho de época", local: "Estoril",
    angle: "Vídeo recap/highlights vendável a equipas",
    link: "https://www.circuito-estoril.pt/en/eventos/",
    redes_sociais: "FB: RaceReadyHistoricRacing · IG: @racereadyiberian", site: "raceready.pt/estorilendurancefestival",
    contacto: "info@raceready.pt",
    notas: "Organizado pela Race Ready, não pelo circuito; datas 4-6 dez não confirmadas na página" },
  { id: "ms-veloso", section: "motorsport", date_label: "recorrente", start_date: null, end_date: null,
    name: "Veloso Motorsport", sub: "Equipa privada, 4 carros no CPV 2026", local: "Nacional",
    angle: "Provavelmente sem media dedicado — abordar no paddock com pacote por corrida/mensal",
    link: "https://velosomotorsport.com/veloso-motorsport-presente-na-edicao-2026-do-campeonato-de-portugal-de-velocidade-com-quatro-carros/",
    redes_sociais: "IG: @velosomotorsport · FB: facebook.com/velosomotorsport", site: "velosomotorsport.com",
    contacto: "geral@velosomotorsport.com · +351 253 632 855", notas: null },

  // ---- Cross-sell auto/moto ----
  { id: "cs-imperio", section: "crosssell", date_label: "recorrente", start_date: null, end_date: null,
    name: "Império Auto Concept", sub: "Stand de usados", local: "Porto",
    angle: "Fotos de stock + reels de chegadas/vendas",
    link: "https://www.imperioautoconcept.com/",
    redes_sociais: "IG: @imperioautoconcept · FB: facebook.com/share/1HGa2Uc1eW", site: "imperioautoconcept.com",
    contacto: "imperioautoconcept@gmail.com · 933 927 443 / 936 498 610", notas: null },
  { id: "cs-tondel", section: "crosssell", date_label: "recorrente", start_date: null, end_date: null,
    name: "Tondel Motors", sub: "Loja de motos", local: "Tondela",
    angle: "Mesmo racional, motos em vez de carros",
    link: "https://guiaempresas.pt/loja-de-motocicletas/tondela/tondel-motors-sa/",
    redes_sociais: "IG: @tondelmotors · FB: TondelMotors | Tondela", site: "tondelmotors.shop",
    contacto: "tondelmotorshop@gmail.com · +351 967 045 607",
    notas: "Nome legal 'Tondelmotors'; site próprio, não guiaempresas.pt" },

  // ---- Feiras B2B ----
  { id: "f-websummit", section: "feiras", date_label: "9–12 nov", start_date: "2026-11-09", end_date: "2026-11-12",
    name: "Web Summit", sub: "O evento em si tem agências oficiais — a oportunidade são os expositores individuais, não o Web Summit",
    local: "Lisboa", angle: "Contactar startups/stands mais pequenos antes: conteúdo próprio em 24-48h para LinkedIn/Instagram deles",
    link: "https://websummit.com/web-summit-2026/",
    redes_sociais: "IG: @websummit · FB: WebSummitHQ · LinkedIn: web-summit", site: "websummit.com/web-summit-2026",
    contacto: "—", notas: "Sem email/telefone público; suporte via support.websummit.com. Conta é global, não específica de Lisboa" },
  { id: "f-autoclassico", section: "feiras", date_label: "10–11 out", start_date: "2026-10-10", end_date: "2026-10-11",
    name: "autoClássico", sub: "Clássicos automóvel e moto — também motorsport", local: "Exponor, Porto",
    angle: "Encaixe direto na marca de fotografia",
    link: "https://exponor.pt/calendario-de-eventos/",
    redes_sociais: "IG: @autoclassico_porto · FB: autoclassicoporto", site: "exponor.pt/calendario/autoclassico",
    contacto: "Tel. geral Exponor: +351 229 981 400 · info@exponor.pt",
    notas: "Página Exponor lista datas 2-5 out divergentes das 10-11 out indicadas — confirmar" },
  { id: "f-segurex", section: "feiras", date_label: "20–22 out", start_date: "2026-10-20", end_date: "2026-10-22",
    name: "SEGUREX", sub: "Segurança", local: "FIL, Lisboa", angle: "Conteúdo de stand para expositores",
    link: "https://www.fil.pt/calendario-fil/",
    redes_sociais: "IG: @segurex_fil · FB: SegurexFIL · LinkedIn: filsegurex", site: "segurex.fil.pt",
    contacto: "segurex@ccl.fil.pt · +351 218 921 500 (geral); Event Manager José Paulo Pinto +351 218 921 558", notas: null },
  { id: "f-logipack", section: "feiras", date_label: "27–29 out", start_date: "2026-10-27", end_date: "2026-10-29",
    name: "LOGIPACK", sub: "Logística/packaging", local: "FIL, Lisboa", angle: "Conteúdo de stand para expositores",
    link: "https://www.fil.pt/calendario-fil/",
    redes_sociais: "IG: @logipack_fil · FB: Logipack · LinkedIn: logipack-fil", site: "logipack.fil.pt",
    contacto: "logipack@ccl.fil.pt", notas: null },
  { id: "f-gamesweek", section: "feiras", date_label: "19–22 nov", start_date: "2026-11-19", end_date: "2026-11-22",
    name: "Lisboa Games Week", sub: null, local: "FIL, Lisboa", angle: "Conteúdo de stand para expositores",
    link: "https://www.fil.pt/calendario-fil/",
    redes_sociais: "IG: @lisboagamesweek", site: "fil.pt/evento/lisboa-games-week",
    contacto: "fil@ccl.fil.pt", notas: "Página FIL lista redes gerais da FIL; @lisboagamesweek existe mas gestão oficial não confirmada" },
  { id: "f-homeing", section: "feiras", date_label: "24–26 set", start_date: "2026-09-24", end_date: "2026-09-26",
    name: "Homeing", sub: "Design de interiores/casa — data corrigida, é já esta semana", local: "Exponor, Porto",
    angle: "Conteúdo de stand para expositores",
    link: "https://exponor.pt/calendario-de-eventos/",
    redes_sociais: "FB: homeing.exponor · IG geral Exponor: @exponor.porto", site: "homeing.exponor.pt",
    contacto: "Tel. geral Exponor: +351 229 981 400 · info@exponor.pt", notas: null },
  { id: "f-fimap", section: "feiras", date_label: "21–24 out", start_date: "2026-10-21", end_date: "2026-10-24",
    name: "Fimap", sub: "Madeira/floresta", local: "Exponor, Porto", angle: "Conteúdo de stand para expositores",
    link: "https://exponor.pt/calendario-de-eventos/",
    redes_sociais: "FB: fimap.exponor · IG geral Exponor: @exponor.porto", site: "exponor.pt/fimap",
    contacto: "fimap@exponor.pt · +351 229 981 400", notas: null },
  { id: "f-decorhotel", section: "feiras", date_label: "4–6 nov", start_date: "2026-11-04", end_date: "2026-11-06",
    name: "DECORHOTEL", sub: "Projeto, construção e decoração para hotelaria — liga direto ao vertical hotelaria",
    local: "Exponor, Porto", angle: "Expositores são fornecedores/decoradores de hotéis — conteúdo de stand + possível pitch recorrente",
    link: "https://exponor.pt/calendario-de-eventos/?data=11",
    redes_sociais: "IG geral Exponor @exponor.porto · FB: exponor.fiporto", site: "exponor.pt/calendario/decorhotel",
    contacto: "Tel. geral Exponor: +351 229 981 400 · info@exponor.pt",
    notas: "Existe conta @expodecorhotel que parece dedicada, mas gestão oficial não confirmada — usar com cautela" },
  { id: "f-expoalimenta", section: "feiras", date_label: "4–6 nov", start_date: "2026-11-04", end_date: "2026-11-06",
    name: "EXPOALIMENTA", sub: "Máquinas e produtos para indústria alimentar — liga ao vertical gastronomia",
    local: "Exponor, Porto", angle: "Conteúdo de stand para expositores",
    link: "https://exponor.pt/calendario-de-eventos/?data=11",
    redes_sociais: "IG/FB geral Exponor: @exponor.porto", site: "exponor.pt/calendario/expoalimenta",
    contacto: "Tel. geral Exponor: +351 229 981 400 · info@exponor.pt", notas: null },
  { id: "f-expocarne", section: "feiras", date_label: "4–6 nov", start_date: "2026-11-04", end_date: "2026-11-06",
    name: "EXPOCARNE", sub: "Indústria de carne", local: "Exponor, Porto", angle: "Conteúdo de stand para expositores",
    link: "https://exponor.pt/calendario-de-eventos/",
    redes_sociais: "IG/FB geral Exponor: @exponor.porto", site: "exponor.pt/calendario/expocarne",
    contacto: "Tel. geral Exponor: +351 229 981 400 · info@exponor.pt", notas: null },
  { id: "f-concreta", section: "feiras", date_label: "18–21 nov", start_date: "2026-11-18", end_date: "2026-11-21",
    name: "Concreta", sub: "Arquitetura, construção e engenharia — liga ao vertical imobiliário",
    local: "Exponor, Porto", angle: "Conteúdo de stand para expositores; construtoras podem virar leads de imobiliário",
    link: "https://exponor.pt/calendario-de-eventos/?data=11",
    redes_sociais: "IG: @thisisconcreta · FB: concretafeira", site: "exponor.pt/concreta",
    contacto: "concreta@exponor.pt · +351 229 981 400", notas: null },
  { id: "f-eletrica", section: "feiras", date_label: "18–21 nov", start_date: "2026-11-18", end_date: "2026-11-21",
    name: "Eletrica", sub: "Energia, mobilidade e material elétrico", local: "Exponor, Porto",
    angle: "Conteúdo de stand para expositores",
    link: "https://exponor.pt/calendario-de-eventos/?data=11",
    redes_sociais: "IG: @eletrica_exponor · FB: eletrica.exponor", site: "exponor.pt/en/eletrica/contacts",
    contacto: "eletrica@exponor.pt · +351 229 981 400", notas: null },
  { id: "f-360tech", section: "feiras", date_label: "26–27 nov", start_date: "2026-11-26", end_date: "2026-11-27",
    name: "360 Tech Industry", sub: "Robótica, automação e indústria 4.0/5.0", local: "Exponor, Porto",
    angle: "Conteúdo de stand para expositores",
    link: "https://exponor.pt/calendario-de-eventos/?data=11",
    redes_sociais: "IG: @360techindustry", site: "exponor.pt/en/360-tech-industry",
    contacto: "360techindustry@exponor.pt · +351 229 981 400", notas: null },

  // ---- Imobiliário ----
  { id: "im-ev-lisboa", section: "imobiliario", date_label: "recorrente", start_date: null, end_date: null,
    name: "Engel & Völkers Lisboa", sub: null, local: "Lisboa",
    angle: "Fotos + vídeo por imóvel novo, ou sessão mensal",
    link: "https://www.engelvoelkers.com/pt/en/shops/lisbon",
    redes_sociais: "IG: @engelvoelkers.lisboa", site: "engelvoelkers.com/pt/en/shops/lisbon",
    contacto: "+351 210 200 490", notas: "Morada: Av. Liberdade 196, 7º, Lisboa" },
  { id: "im-ev-cascais", section: "imobiliario", date_label: "recorrente", start_date: null, end_date: null,
    name: "Engel & Völkers Cascais", sub: null, local: "Cascais", angle: "Mesmo pacote",
    link: "https://www.engelvoelkers.com/pt/en/shops/cascais",
    redes_sociais: "IG: @engelvoelkers.cascais", site: "engelvoelkers.com/pt/en/shops/cascais",
    contacto: "+351 214 860 176", notas: "Também LinkedIn e Facebook próprios" },
  { id: "im-galhofo", section: "imobiliario", date_label: "recorrente", start_date: null, end_date: null,
    name: "Galhofo Real Estate", sub: null, local: "Porto / Lisboa", angle: "Mesmo pacote",
    link: "https://galhoforealestate.com/",
    redes_sociais: "—", site: "galhoforealestate.com",
    contacto: "geral@galhoforealestate.pt",
    notas: "Site não expõe redes sociais próprias; contas do fundador não confirmadas como oficiais da empresa" },

  // ---- Barcos ----
  { id: "bt-bbdouro", section: "barcos", date_label: "recorrente", start_date: null, end_date: null,
    name: "BBDouro Group", sub: null, local: "Porto", angle: "Fotos/vídeo por barco anunciado",
    link: "https://bbdouro.com/en/yachts-brokerage/",
    redes_sociais: "IG: @bbdouro_sailing", site: "bbdouro.com/en/yachts-brokerage",
    contacto: "info@bbdouro.com · +351 935 301 930", notas: "Também LinkedIn: linkedin.com/company/bbdouro" },
  { id: "bt-ybp", section: "barcos", date_label: "recorrente", start_date: null, end_date: null,
    name: "Yachts Broker Portugal", sub: null, local: "Nacional", angle: "Mesmo pacote",
    link: "https://www.yachtsbrokerportugal.com/?lang=en",
    redes_sociais: "—", site: "yachtsbrokerportugal.com",
    contacto: "info@yachtsbrokerportugal.com · +351 289 038 896", notas: "Sediada em Faro/Vilamoura" },
  { id: "bt-palma", section: "barcos", date_label: "recorrente", start_date: null, end_date: null,
    name: "Palmayachts", sub: null, local: "Lisboa / Cascais", angle: "Mesmo pacote",
    link: "https://www.palmayachts.com/pt/",
    redes_sociais: "IG: @palmayachts", site: "palmayachts.com/pt",
    contacto: "info@palmayachts.com · +351 937 065 280",
    notas: "Site atual foca em passeios/charter, não brokerage de venda — confirmar se é a empresa certa" },

  // ---- Vinhos ----
  { id: "vn-martinho", section: "vinhos", date_label: "11 nov", start_date: "2026-11-11", end_date: null,
    name: "São Martinho / Magustos", sub: "Tradição — juntas de freguesia, quintas, associações locais",
    local: "Lisboa & Porto", angle: "Pequena escala real — confirmar organizador local perto da data",
    link: null, redes_sociais: "—", site: "—", contacto: "—", notas: "Categoria genérica, sem organizador fixo, como esperado" },
  { id: "vn-natal", section: "vinhos", date_label: "nov–dez", start_date: null, end_date: null,
    name: "Mercados de Natal", sub: "Ex: Wonderland Lisboa", local: "Lisboa & Porto",
    angle: "Grande público, já muito coberto — baixa prioridade",
    link: null, redes_sociais: "IG: @wonderlandlisboa (FB: wonderlandlisboaoficial)", site: "—",
    contacto: "info@lcpark.com · +351 213 502 060 (via Lisboa Central Park)",
    notas: "Wonderland Lisboa não tem site próprio confirmado; contacto é do hotel organizador" },
  { id: "vn-quintas", section: "vinhos", date_label: "recorrente", start_date: null, end_date: null,
    name: "Quintas do Douro (enoturismo)", sub: null, local: "Douro",
    angle: "Conteúdo de marca/redes sociais fora da vindima",
    link: null, redes_sociais: "—", site: "—", contacto: "—", notas: "Categoria genérica, sem organizador fixo" },
  { id: "vn-restaurantes", section: "vinhos", date_label: "recorrente", start_date: null, end_date: null,
    name: "Restaurantes independentes", sub: null, local: "Lisboa & Porto",
    angle: "Fotos de pratos + conteúdo de redes sociais",
    link: null, redes_sociais: "—", site: "—", contacto: "—", notas: "Categoria genérica, sem organizador fixo" },

  // ---- Congressos médicos em hotéis ----
  { id: "ht-urologia", section: "hoteis", date_label: "9–10 out", start_date: "2026-10-09", end_date: "2026-10-10",
    name: "4º Simpósio de Urologia", sub: "The Southside of Urology", local: "Hotel Tryp Lisboa Caparica Mar",
    angle: "Cobertura + fotos de patrocinadores/stands farmacêuticos", link: null,
    redes_sociais: "Ad Médic (secretariado): LinkedIn/FB/IG @admedic_eventos",
    site: "admedic.pt/eventos/4-simposio-de-urologia-the-southside-of-urology-2026",
    contacto: "paula.cordeiro@admedic.pt · +351 218 429 710",
    notas: "Organizado pelo Serviço de Urologia da ULS Almada-Seixal; redes são do secretariado (Ad Médic)" },
  { id: "ht-cri", section: "hoteis", date_label: "12 out", start_date: "2026-10-12", end_date: null,
    name: "III Jornadas do CRI", sub: "Cirurgia da obesidade", local: "Holiday Inn Lisbon Continental",
    angle: "Cobertura + fotos de patrocinadores", link: null,
    redes_sociais: "—", site: "—", contacto: "—", notas: "Não foi possível localizar página específica deste evento" },
  { id: "ht-nedf", section: "hoteis", date_label: "16–17 out", start_date: "2026-10-16", end_date: "2026-10-17",
    name: "XIX Jornadas NEDF", sub: null, local: "Hotel Tryp Lisboa Caparica Mar",
    angle: "Cobertura + fotos de patrocinadores", link: null,
    redes_sociais: "FB/LinkedIn/IG: @spmedicinainterna", site: "spmi.pt/xix-jornadas-do-nucleo-de-estudos-das-doencas-do-figado",
    contacto: "secretariado@spmi.pt · 217 520 570 (SPMI); paula.cordeiro@admedic.pt",
    notas: "Organizado pelo Núcleo de Estudos das Doenças do Fígado da SPMI" },
  { id: "ht-neuro", section: "hoteis", date_label: "22–23 out", start_date: "2026-10-22", end_date: "2026-10-23",
    name: "1º Congresso SPNI", sub: "Neurorradiologia de Intervenção", local: "Pestana Cidadela, Cascais",
    angle: "Congresso pequeno, 1ª edição — bom para entrar cedo com o organizador", link: null,
    redes_sociais: "—", site: "spni.pt/v2 · admedic.pt/eventos/1-congresso-da-sociedade-portuguesa-de-neurorradiologia-de-intervencao-spni",
    contacto: "paula.cordeiro@admedic.pt · +351 218 429 710", notas: null },
  { id: "ht-geriatria", section: "hoteis", date_label: "30–31 out", start_date: "2026-10-30", end_date: "2026-10-31",
    name: "9ª Reunião Núcleo de Estudos de Geriatria", sub: null, local: "Lagoas Park Hotel, Oeiras",
    angle: "Cobertura + fotos de patrocinadores", link: null,
    redes_sociais: "FB/LinkedIn/IG: @spmedicinainterna", site: "spmi.pt/9a-reuniao-do-nucleo-de-estudos-de-geriatria",
    contacto: "secretariado@spmi.pt · 217 520 570; paula.cordeiro@admedic.pt", notas: "NEGERMI da SPMI" },
  { id: "ht-cardio", section: "hoteis", date_label: "5–6 nov", start_date: "2026-11-05", end_date: "2026-11-06",
    name: "Curso Cardiorenometabólico", sub: null, local: "Lagoas Park Hotel, Oeiras",
    angle: "Cobertura + fotos de patrocinadores", link: null,
    redes_sociais: "Factor Chave (secretariado): FB/IG @factor_chave · LinkedIn", site: "factorchave.com/curso-cardiorenometabolico-2026",
    contacto: "secretariado@factorchave.pt", notas: "Grupo de Trabalho de Cardiorenometabólicas da Soc. Port. de Nefrologia" },
  { id: "ht-onco", section: "hoteis", date_label: "12–13 nov", start_date: "2026-11-12", end_date: "2026-11-13",
    name: "4º Encontro Multidisciplinar de Oncologia Urológica", sub: null, local: "Hotel Axis, Porto",
    angle: "Cobertura + fotos de patrocinadores", link: null,
    redes_sociais: "Factor Chave (secretariado): FB/IG @factor_chave · LinkedIn", site: "factorchave.com/4o-encontro-multidisciplinar-de-oncologia-urologica",
    contacto: "secretariado@factorchave.pt", notas: "Apoio dos Serviços de Oncologia/Urologia da ULS São João" },
  { id: "ht-pediatrica", section: "hoteis", date_label: "12–13 nov", start_date: "2026-11-12", end_date: "2026-11-13",
    name: "XXVIII Congresso Nacional de Medicina Intensiva Pediátrica", sub: null, local: "Hotel HF Ipanema Porto",
    angle: "Cobertura + fotos de patrocinadores", link: null,
    redes_sociais: "Ad Médic (secretariado): LinkedIn/FB/IG @admedic_eventos", site: "admedic.pt/eventos/xxviii-congresso-nacional-de-medicina-intensiva-pediatrica",
    contacto: "paula.cordeiro@admedic.pt · +351 218 429 710", notas: "Organizado pela Sociedade de Cuidados Intensivos Pediátricos (SCIP)" },
  { id: "ht-pathology", section: "hoteis", date_label: "19–20 nov", start_date: "2026-11-19", end_date: "2026-11-20",
    name: "AI & Digital Pathology Summit", sub: null, local: "ICBAS | IPO Porto",
    angle: "Não é hotel, mas mesma lógica — patrocinadores tech/farma", link: null,
    redes_sociais: "—", site: "—", contacto: "—", notas: "Nenhuma presença web pública indexada encontrada; pode ser pequena escala" },
  { id: "ht-urobootcamp", section: "hoteis", date_label: "20 nov", start_date: "2026-11-20", end_date: null,
    name: "Bootcamp de Urologia ESU Lisboa 2026", sub: null, local: "Hospital das Forças Armadas, Lisboa",
    angle: "Cobertura + fotos de patrocinadores", link: null,
    redes_sociais: "Associação Portuguesa de Urologia (APU): FB", site: "apurologia.pt/eventos · admedic.pt/eventos/bootcamp-de-urologia-da-esu-lisboa-2026",
    contacto: "apu@apurologia.pt · 213 243 590 (APU); paula.cordeiro@admedic.pt · +351 218 429 710",
    notas: "Organizado pela APU em parceria com a ESU (European School of Urology)" },
  { id: "ht-idosos", section: "hoteis", date_label: "21 nov", start_date: "2026-11-21", end_date: null,
    name: "4ª Reunião da Associação dos Médicos dos Idosos Institucionalizados", sub: null, local: "Ordem dos Médicos, Lisboa",
    angle: "Cobertura + fotos de patrocinadores", link: null,
    redes_sociais: "AMIDI: FB/LinkedIn/IG @associacao.midi", site: "amidi.pt",
    contacto: "geral@amidi.pt · associacao.midi@gmail.com · 91 732 76 94", notas: null },
  { id: "ht-obesidade", section: "hoteis", date_label: "26–28 nov", start_date: "2026-11-26", end_date: "2026-11-28",
    name: "30º Congresso Português de Obesidade", sub: null, local: "Hotel Pestana Douro Riverside, Porto",
    angle: "Congresso maior, 30ª edição — provavelmente já tem fornecedor, mas vale contactar", link: null,
    redes_sociais: "FB: @speo.pt", site: "speo-obesidade.pt",
    contacto: "speo@sapo.pt · +351 213 904 065 (SPEO); sofia.gomes@admedic.pt",
    notas: "Sociedade Portuguesa para o Estudo da Obesidade; secretariado do evento via Ad Médic" },
  { id: "ht-eunetccc", section: "hoteis", date_label: "26–27 nov", start_date: "2026-11-26", end_date: "2026-11-27",
    name: "EUnetCCC Annual Meeting", sub: "Internacional", local: "Centro de Congressos de Lisboa",
    angle: "Público internacional — bom para portfolio em inglês", link: null,
    redes_sociais: "LinkedIn/FB/IG: @eunetccc", site: "eunetccc2026.eu · eunetccc.eu",
    contacto: "secretariado@factorchave.pt", notas: "Secretariado local gerido pela Factor Chave" },
  { id: "ht-apfh", section: "hoteis", date_label: "19–21 nov", start_date: "2026-11-19", end_date: "2026-11-21",
    name: "XIX Congresso Nacional APFH", sub: "Farmacêuticos Hospitalares — grande, provavelmente já coberto", local: "MEO Arena, Lisboa",
    angle: "Baixa prioridade — mas dezenas de stands de farmacêuticas lá dentro, individualmente", link: null,
    redes_sociais: "IG: @apfh_farmaceuticoshospitalares · LinkedIn: apfh",
    site: "apfh.pt/congresso-nacional/xix-congresso-nacional-apfh-19-20-e-21-de-novembro-de-2026-meo-arena-lisboa",
    contacto: "—", notas: "Página confirmada; email/telefone do secretariado não verificável (robots.txt)" },

  // ---- Outros ----
  { id: "ot-modalisboa", section: "outros", date_label: "7–11 out", start_date: "2026-10-07", end_date: "2026-10-11",
    name: "ModaLisboa Priority", sub: "Fashion week oficial — imprensa acreditada já fechada, baixa prioridade",
    local: "Lisboa", angle: "Ângulo real: designers/desfiles fora do calendário principal, não o evento oficial",
    link: "https://modalisboa.pt/en/editions/",
    redes_sociais: "IG: @lisboafashionweek · FB: ModaLisboa", site: "modalisboa.pt",
    contacto: "modalisboa@modalisboa.pt · +351 21 321 30 00", notas: "Delegação Porto: modalisboa.porto@modalisboa.pt · +351 22 099 36 23" },
  { id: "ot-hoteis", section: "outros", date_label: "sem Q4", start_date: null, end_date: null,
    name: "Hotéis boutique — sem aberturas confirmadas out–dez", sub: null, local: "Lisboa & Porto",
    angle: "Oportunidade real é pitch recorrente a hotéis já a operar, não \"abertura\"",
    link: null, redes_sociais: "—", site: "—", contacto: "—", notas: "Categoria genérica, sem entidade específica" },
  { id: "ot-tech", section: "outros", date_label: "sem data fixa", start_date: null, end_date: null,
    name: "Meetups tech/startups locais", sub: null, local: "Lisboa & Porto",
    angle: "Vivem em Meetup/Eventbrite com pouca antecedência — monitorizar",
    link: null, redes_sociais: "—", site: "—", contacto: "—",
    notas: "Grupo recorrente conhecido: Lisbon New Tech Meetup (meetup.com/lisbon-new-tech-meetup) — referência genérica" },
  { id: "ot-musica", section: "outros", date_label: "sem data fixa", start_date: null, end_date: null,
    name: "Festivais/concertos de pequena escala", sub: null, local: "Lisboa & Porto",
    angle: "Não encontrei fontes fiáveis com datas — provavelmente Instagram/bilheteira local",
    link: null, redes_sociais: "—", site: "—", contacto: "—", notas: "Categoria genérica, sem entidade específica" },

  // ---- Continental ----
  { id: "ct-olaspro", section: "continental", date_label: "23–25 out", start_date: "2026-10-23", end_date: "2026-10-25",
    name: "Olas Pro Ericeira", sub: "Circuito de acesso à elite mundial do surf", local: "Ericeira — a tua zona, zero deslocação",
    angle: "Melhor relação esforço/retorno de toda a lista — é literalmente em casa", link: null,
    redes_sociais: "IG: @ericeirasurfclube · FB", site: "ericeirasurfclube.com",
    contacto: "geral@ericeirasurfclube.com",
    notas: "Datas/formato não totalmente confirmados; possível confusão com EDP/MEO Ericeira Pro (WSL Challenger Series)" },
  { id: "ct-bodyboard", section: "continental", date_label: "3–4 out", start_date: "2026-10-03", end_date: "2026-10-04",
    name: "CN Bodyboard Esperanças", sub: null, local: "Ericeira",
    angle: "Zero deslocação, categorias jovens — pais compram fotos/vídeo", link: null,
    redes_sociais: "IG: @fps_oficial · FB: FPSurf", site: "surfingportugal.com/cn-bb-esp",
    contacto: "fps@surfingportugal.com · +351 219 228 914", notas: "Federação Portuguesa de Surf; também via Ericeira Surf Clube" },
  { id: "ct-escinv", section: "continental", date_label: "dez (a confirmar)", start_date: null, end_date: null,
    name: "ESC Invitational", sub: null, local: "Ericeira", angle: "Zero deslocação", link: null,
    redes_sociais: "IG: @ericeirasurfclube", site: "ericeirasurfclube.com/ericeira-surf-clube-invitational-2025",
    contacto: "geral@ericeirasurfclube.com", notas: "Edição 2025 exclusiva para atletas do clube; data de dez 2026 não confirmada" },
  { id: "ct-ripcurl", section: "continental", date_label: "16–25 out", start_date: "2026-10-16", end_date: "2026-10-25",
    name: "MEO Rip Curl Pro Portugal", sub: "WSL Championship Tour — cobertura oficial já fechada", local: "Supertubos, Peniche",
    angle: "Não vender cobertura do contest — vender conteúdo às marcas com vila/ativação na praia", link: null,
    redes_sociais: "@wsl (sem IG dedicado próprio)", site: "worldsurfleague.com/events/2026/ct/445/meo-rip-curl-pro-portugal/main",
    contacto: "—", notas: null },
  { id: "ct-nazare", section: "continental", date_label: "prov. nov 2026 – mar 2027 (a confirmar)", start_date: null, end_date: null,
    name: "TUDOR Nazaré Big Wave Challenge", sub: "Funciona por \"green light\" (swell), não data fixa", local: "Praia do Norte, Nazaré",
    angle: "Maior prestígio de conteúdo de surf em Portugal — marcas pagam bem, mas é preciso estar pronto a ir de repente", link: null,
    redes_sociais: "—", site: "nazarequalifica.pt/en",
    contacto: "+351 262 550 010 · +351 934 000 126",
    notas: "Organizador local: Nazaré Qualifica; evento em parceria TUDOR/WSL Big Wave Tour" },
  { id: "ct-golega", section: "continental", date_label: "6–15 nov", start_date: "2026-11-06", end_date: "2026-11-15",
    name: "Feira Nacional do Cavalo", sub: "50ª edição — cultura equestre de elite", local: "Golegã",
    angle: "Criadores/proprietários de cavalos de luxo — bom para pitch recorrente tipo imobiliário/barcos", link: null,
    redes_sociais: "IG: @feiranacionaldocavalo_oficial · FB: feira.cavalo", site: "feiranacionaldocavalo.com",
    contacto: "Secretariado: +351 249 979 122 · Equuspolis: +351 249 979 000 · Turismo: +351 249 979 002 · CM Golegã: +351 249 979 050",
    notas: "E-mails protegidos por Cloudflare, não extraíveis" },
  { id: "ct-portalegre", section: "continental", date_label: "15–17 out", start_date: "2026-10-15", end_date: "2026-10-17",
    name: "BP Ultimate Baja de Portalegre 500", sub: null, local: "Portalegre",
    angle: "Baja grande, equipas com patrocínio", link: null,
    redes_sociais: "IG: @bajaportalegre · FB: BajaPortalegre500", site: "bajaportalegre500.com",
    contacto: "—", notas: "Pontua no FIA European Bajas Cup" },
  { id: "ct-algarve-rally", section: "continental", date_label: "2–3 out", start_date: "2026-10-02", end_date: "2026-10-03",
    name: "Rallye Casinos do Algarve", sub: null, local: "Algarve", angle: "—", link: null,
    redes_sociais: "IG: @clube_automovel_do_algarve · FB: CAAlgarve", site: "rallyecasinosdoalgarve.com · clubeautomovelalgarve.pt",
    contacto: "geral.caa@gmail.com · +351 289 422 145", notas: "Organizador: Clube Automóvel do Algarve" },
  { id: "ct-rallyx", section: "continental", date_label: "23–25 out", start_date: "2026-10-23", end_date: "2026-10-25",
    name: "Rally X Global Final", sub: null, local: "Montalegre",
    angle: "Final internacional — equipas com orçamento", link: null,
    redes_sociais: "FB: MontalegreCircuit", site: "montalegrecircuit.pt · rallyx.se/schedule/montalegre",
    contacto: "—", notas: null },
  { id: "ct-bajalagos", section: "continental", date_label: "27–29 nov", start_date: "2026-11-27", end_date: "2026-11-29",
    name: "Baja de Lagos", sub: null, local: "Lagos, Algarve", angle: "—", link: null,
    redes_sociais: "IG: @clube_automovel_do_algarve · FB: CAAlgarve", site: "clubeautomovelalgarve.pt",
    contacto: "geral.caa@gmail.com · +351 289 422 145", notas: "Mesmo organizador do Rallye Casinos do Algarve" },
  { id: "ct-fronteira", section: "continental", date_label: "3–6 dez", start_date: "2026-12-03", end_date: "2026-12-06",
    name: "24h TT Vila de Fronteira", sub: null, local: "Fronteira, Portalegre",
    angle: "Prova de 24h — bom para vídeo de resistência/highlights", link: null,
    redes_sociais: "IG: @24horastt · FB: 24horastt", site: "24horastt.com",
    contacto: "—", notas: null },
  { id: "ct-coimbra", section: "continental", date_label: "9 out", start_date: "2026-10-09", end_date: null,
    name: "XI Reunião Doença Vascular Pulmonar", sub: null, local: "Hotel NH D. Inês, Coimbra",
    angle: "Congresso médico, patrocinadores farmacêuticos", link: null,
    redes_sociais: "FB/IG/LinkedIn: @spmedicinainterna", site: "spmi.pt/xi-reuniao-anual-do-nucleo-de-estudos-de-doenca-vascular-pulmonar",
    contacto: "paula.cordeiro@admedic.pt; secretariado@spmi.pt · 217 520 570", notas: "NEDVP da SPMI" },
  { id: "ct-apu", section: "continental", date_label: "29 out–1 nov", start_date: "2026-10-29", end_date: "2026-11-01",
    name: "XIX Simposio APU", sub: null, local: "Eurostars Oasis Plaza, Figueira da Foz",
    angle: "Congresso médico, patrocinadores farmacêuticos", link: null,
    redes_sociais: "IG/FB/LinkedIn/X: @apurologia", site: "admedic.pt/eventos/xix-simposio-apu.html · apurologia.pt",
    contacto: "+351 218 429 710 (secretariado Admedic)", notas: "APU = Associação Portuguesa de Urologia" },
  { id: "ct-lagoa", section: "continental", date_label: "29–30 out", start_date: "2026-10-29", end_date: "2026-10-30",
    name: "Jornadas de Ginecologia e Obstetrícia", sub: null, local: "Centro de Congressos de Lagoa, Algarve",
    angle: "Congresso médico, patrocinadores farmacêuticos", link: null,
    redes_sociais: "—", site: "admedic.pt/eventos/jornadas-de-ginecologia-e-obstetricia.html",
    contacto: "+351 218 429 710 (secretariado Admedic)", notas: "AFIMBA / Serviço de Ginecologia e Obstetrícia da ULS Algarve" },
  { id: "ct-fatima", section: "continental", date_label: "6–7 nov", start_date: "2026-11-06", end_date: "2026-11-07",
    name: "18ª Conferência de Valor APAH", sub: null, local: "Divine Fátima Hotel, Fátima",
    angle: "Congresso médico, patrocinadores farmacêuticos", link: null,
    redes_sociais: "LinkedIn/FB/YouTube: APAH", site: "admedic.pt/en/events/18-conferencia-de-valor-apah-2026.html · apah.pt",
    contacto: "+351 21 842 97 10 (secretariado Admedic)", notas: null },
  { id: "ct-hotelariahosp", section: "continental", date_label: "12–13 nov", start_date: "2026-11-12", end_date: "2026-11-13",
    name: "XII Jornadas Associação Portuguesa de Hotelaria Hospitalar", sub: null, local: "Eurostars Oasis Plaza, Figueira da Foz",
    angle: "Congresso médico, patrocinadores farmacêuticos", link: null,
    redes_sociais: "FB: hotelaria.hospitalar.pt", site: "aphh.pt",
    contacto: "info@admedic.pt · +351 218 429 710 (secretariado Admedic)", notas: null },
  { id: "ct-apnug", section: "continental", date_label: "27–28 nov", start_date: "2026-11-27", end_date: "2026-11-28",
    name: "XVII Congresso APNUG", sub: null, local: "Hotel Meliá Ria, Aveiro",
    angle: "Congresso médico, patrocinadores farmacêuticos", link: null,
    redes_sociais: "—", site: "apnug.pt · apnug.pt/wp/index.php/congressos",
    contacto: "apnug@apnug.pt", notas: "APNUG = Associação Portuguesa de Neurourologia e Uroginecologia" },
  { id: "ct-peniche-med", section: "continental", date_label: "12 dez", start_date: "2026-12-12", end_date: null,
    name: "8ª Reunião Núcleo de Estudos de Prevenção e Risco Vascular", sub: null, local: "Hotel MH Atlântico, Peniche",
    angle: "Congresso médico, patrocinadores farmacêuticos", link: null,
    redes_sociais: "FB/IG/LinkedIn: @spmedicinainterna", site: "spmi.pt/8a-reuniao-nucleo-de-estudos-de-prevencao-e-risco-vascular",
    contacto: "paula.cordeiro@admedic.pt; secretariado@spmi.pt · 217 520 570", notas: "NEPRV da SPMI" },
];
